// Re-export auto-generated Wails bindings with proper types.
// The bindings are generated by `wails3 generate bindings`.

import {
  ChatService as _Chat,
  FileService as _File,
} from "../../bindings/github.com/mossagents/moss/examples/mosswork-desktop/index.js";

export const ChatService = {
  sendMessage: (content: string) => _Chat.SendMessage(content),
  sendMessageWithAttachments: (content: string, files: string[]) =>
    _Chat.SendMessageWithAttachments(content, files),
  stopAgent: () => _Chat.StopAgent(),
  respondToAsk: (response: string, approved = true) =>
    _Chat.RespondToAsk(response, approved),
  newSession: () => _Chat.NewSession(),
  getConfig: () => _Chat.GetConfig(),
  isRunning: () => _Chat.IsRunning(),
  sendCommand: (command: string) => _Chat.SendMessage(command),
  addAutomation: (id: string, schedule: string, goal: string) => _Chat.AddAutomation(id, schedule, goal),
  removeAutomation: (id: string) => _Chat.RemoveAutomation(id),
  getAutomations: () => _Chat.GetAutomations(),
  runAutomationNow: (id: string) => _Chat.RunAutomationNow(id),
  getSettings: () => _Chat.GetSettings(),
  getPresetModels: () => _Chat.GetPresetModels(),
  updateModel: (provider: string, model: string, baseURL: string, apiKey: string) =>
    _Chat.UpdateModel(provider, model, baseURL, apiKey),
  deleteSession: (id: string) => _Chat.DeleteSession(id),
  deleteSessions: (ids: string[]) => _Chat.DeleteSessions(ids),
  resumeSession: (id: string) => _Chat.ResumeSession(id),
  getSessionHistory: (id: string) => _Chat.GetSessionHistory(id),
  getTools: () => _Chat.GetTools(),
  getSkills: () => _Chat.GetSkills(),
};

export const FileService = {
  openFiles: () => _File.OpenFiles(),
  openImages: () => _File.OpenImages(),
  getWorkspace: () => _File.GetWorkspace(),
};
