// Re-export auto-generated Wails bindings with proper types.
// The bindings are generated by `wails3 generate bindings`.

import {
  ChatService as _Chat,
  FileService as _File,
} from "../../bindings/github.com/mossagents/moss/examples/mosswork-desktop";

export const ChatService = {
  sendMessage: (content: string) => _Chat.SendMessage(content),
  sendMessageWithAttachments: (content: string, files: string[]) =>
    _Chat.SendMessageWithAttachments(content, files),
  stopAgent: () => _Chat.StopAgent(),
  respondToAsk: (response: string, approved = true) =>
    _Chat.RespondToAsk(response, approved),
  newSession: () => _Chat.NewSession(),
  getConfig: () => _Chat.GetConfig(),
  isRunning: () => _Chat.IsRunning(),
  sendCommand: (command: string) => _Chat.SendMessage(command),
};

export const FileService = {
  openFiles: () => _File.OpenFiles(),
  openImages: () => _File.OpenImages(),
  getWorkspace: () => _File.GetWorkspace(),
};
