// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetWorkspace(): $CancellablePromise<string> {
    return $Call.ByID(940003286);
}

export function ListWorkspaceFiles(pattern: string): $CancellablePromise<string[]> {
    return $Call.ByID(267893223, pattern).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(606221006).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenImages(): $CancellablePromise<string[]> {
    return $Call.ByID(3229562157).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ReadFileBase64(path: string): $CancellablePromise<string> {
    return $Call.ByID(1315397022, path);
}

export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(1738858927);
}

export function UploadToWorkspace(srcPath: string): $CancellablePromise<string> {
    return $Call.ByID(1969114056, srcPath);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
