// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 桥接 moss kernel 与桌面前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetConfig(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(889101375).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDashboard(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1605919923).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(2401099782);
}

export function NewSession(): $CancellablePromise<void> {
    return $Call.ByID(787229693);
}

export function RespondToAsk(value: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(1013399822, value, approved);
}

export function ResumeSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3201944292, id);
}

export function SendMessage(content: string): $CancellablePromise<void> {
    return $Call.ByID(1063940756, content);
}

export function SendMessageWithAttachments(content: string, attachments: string[]): $CancellablePromise<void> {
    return $Call.ByID(1831210734, content, attachments);
}

export function StopAgent(): $CancellablePromise<void> {
    return $Call.ByID(429619256);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
