// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 桥接 moss kernel 与桌面前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAutomation creates or replaces a scheduled automation task.
 */
export function AddAutomation(id: string, schedule: string, goal: string): $CancellablePromise<void> {
    return $Call.ByID(1862023689, id, schedule, goal);
}

/**
 * GetAutomations returns all scheduled tasks.
 */
export function GetAutomations(): $CancellablePromise<$models.scheduleView[]> {
    return $Call.ByID(3094061219).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetConfig(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(889101375).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetDashboard(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1605919923).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetPresetModels returns the built-in list of known LLM providers and models.
 */
export function GetPresetModels(): $CancellablePromise<$models.ModelPreset[]> {
    return $Call.ByID(3853313952).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetSettings returns the current active model/provider settings (API key masked).
 */
export function GetSettings(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1831475952).then(($result: any) => {
        return $$createType2($result);
    });
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(2401099782);
}

export function NewSession(): $CancellablePromise<void> {
    return $Call.ByID(787229693);
}

/**
 * RemoveAutomation removes a scheduled task by ID.
 */
export function RemoveAutomation(id: string): $CancellablePromise<void> {
    return $Call.ByID(2305826584, id);
}

export function RespondToAsk(value: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(1013399822, value, approved);
}

export function ResumeSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3201944292, id);
}

/**
 * RunAutomationNow triggers an automation task immediately (fire-and-forget).
 */
export function RunAutomationNow(id: string): $CancellablePromise<void> {
    return $Call.ByID(1778526165, id);
}

export function SendMessage(content: string): $CancellablePromise<void> {
    return $Call.ByID(1063940756, content);
}

export function SendMessageWithAttachments(content: string, attachments: string[]): $CancellablePromise<void> {
    return $Call.ByID(1831210734, content, attachments);
}

export function StopAgent(): $CancellablePromise<void> {
    return $Call.ByID(429619256);
}

/**
 * UpdateModel hot-reloads the kernel with a new provider/model/key configuration.
 * Returns an error if an agent is currently running.
 */
export function UpdateModel(provider: string, model: string, baseURL: string, apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(4129383295, provider, model, baseURL, apiKey);
}

// Private type creation functions
const $$createType0 = $models.scheduleView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.ModelPreset.createFrom;
const $$createType4 = $Create.Array($$createType3);
