// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 桥接 moss kernel 与桌面前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAutomation creates or replaces a scheduled automation task.
 * @param {string} id
 * @param {string} schedule
 * @param {string} goal
 * @returns {$CancellablePromise<void>}
 */
export function AddAutomation(id, schedule, goal) {
    return $Call.ByID(1862023689, id, schedule, goal);
}

/**
 * DeleteSession removes a single session by ID.
 * If the deleted session is the current active session, the active session is cleared.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(id) {
    return $Call.ByID(3245855500, id);
}

/**
 * DeleteSessions removes multiple sessions by ID in one call.
 * Errors from individual deletions are collected and returned as a combined error.
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSessions(ids) {
    return $Call.ByID(245493997, ids);
}

/**
 * GetAutomations returns all scheduled tasks.
 * @returns {$CancellablePromise<$models.scheduleView[]>}
 */
export function GetAutomations() {
    return $Call.ByID(3094061219).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetConfig() {
    return $Call.ByID(889101375).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetDashboard() {
    return $Call.ByID(1605919923).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetPresetModels returns the built-in list of known LLM providers and models.
 * @returns {$CancellablePromise<$models.ModelPreset[]>}
 */
export function GetPresetModels() {
    return $Call.ByID(3853313952).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetSettings returns the current active model/provider settings (API key masked).
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSettings() {
    return $Call.ByID(1831475952).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRunning() {
    return $Call.ByID(2401099782);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function NewSession() {
    return $Call.ByID(787229693);
}

/**
 * RemoveAutomation removes a scheduled task by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAutomation(id) {
    return $Call.ByID(2305826584, id);
}

/**
 * @param {string} value
 * @param {boolean} approved
 * @returns {$CancellablePromise<void>}
 */
export function RespondToAsk(value, approved) {
    return $Call.ByID(1013399822, value, approved);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ResumeSession(id) {
    return $Call.ByID(3201944292, id);
}

/**
 * RunAutomationNow triggers an automation task immediately (fire-and-forget).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RunAutomationNow(id) {
    return $Call.ByID(1778526165, id);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(content) {
    return $Call.ByID(1063940756, content);
}

/**
 * @param {string} content
 * @param {string[]} attachments
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageWithAttachments(content, attachments) {
    return $Call.ByID(1831210734, content, attachments);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopAgent() {
    return $Call.ByID(429619256);
}

/**
 * UpdateModel hot-reloads the kernel with a new provider/model/key configuration.
 * Returns an error if an agent is currently running.
 * @param {string} provider
 * @param {string} model
 * @param {string} baseURL
 * @param {string} apiKey
 * @returns {$CancellablePromise<void>}
 */
export function UpdateModel(provider, model, baseURL, apiKey) {
    return $Call.ByID(4129383295, provider, model, baseURL, apiKey);
}

// Private type creation functions
const $$createType0 = $models.scheduleView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.ModelPreset.createFrom;
const $$createType4 = $Create.Array($$createType3);
