// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkspace() {
    return $Call.ByID(940003286);
}

/**
 * @param {string} pattern
 * @returns {$CancellablePromise<string[]>}
 */
export function ListWorkspaceFiles(pattern) {
    return $Call.ByID(267893223, pattern).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function OpenFiles() {
    return $Call.ByID(606221006).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function OpenImages() {
    return $Call.ByID(3229562157).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFileBase64(path) {
    return $Call.ByID(1315397022, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(1738858927);
}

/**
 * @param {string} srcPath
 * @returns {$CancellablePromise<string>}
 */
export function UploadToWorkspace(srcPath) {
    return $Call.ByID(1969114056, srcPath);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
