// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ModelPreset describes a known LLM model combination.
 * Provider is the canonical API type (openai-completions, openai-responses, claude, gemini).
 * Group is a display sub-group for grouping models within the same API type (e.g. "openai", "deepseek", "ollama").
 */
export class ModelPreset {
    "provider": string;
    "group"?: string;
    "label": string;
    "model": string;
    "base_url"?: string;

    /** Creates a new ModelPreset instance. */
    constructor($$source: Partial<ModelPreset> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelPreset instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelPreset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelPreset($$parsedSource as Partial<ModelPreset>);
    }
}

export class scheduleView {
    "id": string;
    "schedule": string;
    "goal": string;
    "run_count": number;
    "last_run"?: string;
    "next_run"?: string;

    /** Creates a new scheduleView instance. */
    constructor($$source: Partial<scheduleView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("schedule" in $$source)) {
            this["schedule"] = "";
        }
        if (!("goal" in $$source)) {
            this["goal"] = "";
        }
        if (!("run_count" in $$source)) {
            this["run_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new scheduleView instance from a string or object.
     */
    static createFrom($$source: any = {}): scheduleView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new scheduleView($$parsedSource as Partial<scheduleView>);
    }
}
