// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HistoryMessage is a frontend-friendly representation of a session message.
 */
export class HistoryMessage {
    "role": string;
    "content": string;
    "thinking"?: string;
    "tools"?: HistoryTool[];

    /** Creates a new HistoryMessage instance. */
    constructor($$source: Partial<HistoryMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryMessage {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField3_0($$parsedSource["tools"]);
        }
        return new HistoryMessage($$parsedSource as Partial<HistoryMessage>);
    }
}

/**
 * HistoryTool represents a single tool call and its result from session history.
 */
export class HistoryTool {
    "name": string;
    "input"?: string;
    "result"?: string;
    "is_error"?: boolean;

    /** Creates a new HistoryTool instance. */
    constructor($$source: Partial<HistoryTool> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryTool instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryTool {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryTool($$parsedSource as Partial<HistoryTool>);
    }
}

/**
 * ModelPreset describes a known LLM model combination.
 * Provider is the canonical API type (openai-completions, openai-responses, claude, gemini).
 * Group is a display sub-group for grouping models within the same API type (e.g. "openai", "deepseek", "ollama").
 */
export class ModelPreset {
    "provider": string;
    "group"?: string;
    "label": string;
    "model": string;
    "base_url"?: string;

    /** Creates a new ModelPreset instance. */
    constructor($$source: Partial<ModelPreset> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelPreset instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelPreset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelPreset($$parsedSource as Partial<ModelPreset>);
    }
}

/**
 * ToolInfo is a frontend-friendly summary of a registered tool.
 */
export class ToolInfo {
    "name": string;
    "description": string;
    "risk": string;
    "source"?: string;

    /** Creates a new ToolInfo instance. */
    constructor($$source: Partial<ToolInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("risk" in $$source)) {
            this["risk"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolInfo($$parsedSource as Partial<ToolInfo>);
    }
}

export class scheduleView {
    "id": string;
    "schedule": string;
    "goal": string;
    "run_count": number;
    "last_run"?: string;
    "next_run"?: string;

    /** Creates a new scheduleView instance. */
    constructor($$source: Partial<scheduleView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("schedule" in $$source)) {
            this["schedule"] = "";
        }
        if (!("goal" in $$source)) {
            this["goal"] = "";
        }
        if (!("run_count" in $$source)) {
            this["run_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new scheduleView instance from a string or object.
     */
    static createFrom($$source: any = {}): scheduleView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new scheduleView($$parsedSource as Partial<scheduleView>);
    }
}

// Private type creation functions
const $$createType0 = HistoryTool.createFrom;
const $$createType1 = $Create.Array($$createType0);
