// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HistoryMessage is a frontend-friendly representation of a session message.
 */
export class HistoryMessage {
    /**
     * Creates a new HistoryMessage instance.
     * @param {Partial<HistoryMessage>} [$$source = {}] - The source object to create the HistoryMessage.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["thinking"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HistoryTool[] | undefined}
             */
            this["tools"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryMessage}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField3_0($$parsedSource["tools"]);
        }
        return new HistoryMessage(/** @type {Partial<HistoryMessage>} */($$parsedSource));
    }
}

/**
 * HistoryTool represents a single tool call and its result from session history.
 */
export class HistoryTool {
    /**
     * Creates a new HistoryTool instance.
     * @param {Partial<HistoryTool>} [$$source = {}] - The source object to create the HistoryTool.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["input"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["result"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["is_error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryTool instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryTool}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryTool(/** @type {Partial<HistoryTool>} */($$parsedSource));
    }
}

/**
 * ModelPreset describes a known LLM model combination.
 * Provider is the canonical API type (openai-completions, openai-responses, claude, gemini).
 * Group is a display sub-group for grouping models within the same API type (e.g. "openai", "deepseek", "ollama").
 */
export class ModelPreset {
    /**
     * Creates a new ModelPreset instance.
     * @param {Partial<ModelPreset>} [$$source = {}] - The source object to create the ModelPreset.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["group"] = undefined;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["base_url"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelPreset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelPreset(/** @type {Partial<ModelPreset>} */($$parsedSource));
    }
}

/**
 * ToolInfo is a frontend-friendly summary of a registered tool.
 */
export class ToolInfo {
    /**
     * Creates a new ToolInfo instance.
     * @param {Partial<ToolInfo>} [$$source = {}] - The source object to create the ToolInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("risk" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["risk"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolInfo(/** @type {Partial<ToolInfo>} */($$parsedSource));
    }
}

export class scheduleView {
    /**
     * Creates a new scheduleView instance.
     * @param {Partial<scheduleView>} [$$source = {}] - The source object to create the scheduleView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("schedule" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schedule"] = "";
        }
        if (!("goal" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goal"] = "";
        }
        if (!("run_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["run_count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_run"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["next_run"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new scheduleView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {scheduleView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new scheduleView(/** @type {Partial<scheduleView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = HistoryTool.createFrom;
const $$createType1 = $Create.Array($$createType0);
